services:
  - type: web
    name: traffic-frnd-backend
    env: node
    rootDir: server
    plan: free
    buildCommand: npm ci || npm install && npm run build
    startCommand: node server.js
    autoDeploy: true
    healthCheckPath: /api/health

